### ISSUE TITLE
Update map "view more info" layout

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/MallMap#17]
On the map, when you click View More Info, the modal overlay needs some revision to work better with the walking tour functionality. 

Currently, the info panel shows back to map button top left, item title at top of window, date and description fields in the body, then an image and finally the View More Info button below the image. 

We want to make the following changes:

- Add a Next Tour Stop link to the top right to advance along the tour within the window
- Replace item title at top of window with Tour Title and keep consistent throughout tours
- Replace date with Item title and wrap in h2 tags instead of p
- Replace "View More Info" text with "See Full Details" 
- Change bright yellow color to match mall-theme color scheme
- Explore possibilities of making the image and text content side by side on desktop displays, maybe using flexbox similar to the way [thinglink image/text modals](https://www.thinglink.com/scene/1693995599986164516) are styled.

Also, we want to use the Abstract field content here if it exists, and fallback to Description only if empty. 

Relevant files are mallmap.js and IndexController, where data is built in getItemAction() function.

![image](https://user-images.githubusercontent.com/10544799/226175454-4e73d8a7-3803-4a05-916a-fa64cf926bd6.png)

**Comment by tutingjun** [comment]
Make the view more button in the item page link to a new page
