### ISSUE TITLE
Marker click issue with zoom levels and bounds

### ISSUE THREAD

**Issue by apjmason** [DigitalCarleton/MallMap#37]
The issue we've been having I think is related to the [map.flyTo method](https://leafletjs.com/reference.html#map-flyto), which takes an optional zoom parameter. The two places it shows up it's hard coded to 16, e.g. https://github.com/DigitalCarleton/MallMap/blob/485f8740fa198f8f92db5cde8bcde42917978226/views/public/javascripts/walking-tour.js#L625

Can you all test what happens when we a) remove the zoom parameter — I assume it will stay at current zoom? b) get one of the zoom parameters set in the config options and use that instead.

**Comment by tutingjun** [comment]
We update the js file such that the zoom level is not hardcoded. Whenever it did a `flyTo`, it will be the max zoom of the map setting.
