### ISSUE TITLE
Mall map theming to match overall

### ISSUE THREAD

**Issue by tutingjun** [DigitalCarleton/MallMap#9]
The yellow color on the walking tour map is different than the themes. Is the mall-map.css controlling those in the plugin? If so, we should think about how to reconcile without duplicating much work.

See, for example, a details view or filter on [this page](https://omeka-dev-2022.carleton.edu/cgmrdev/map)

**Comment by tutingjun** [comment]
@apjmason Which color should we choose? Color of the website title?

**Comment by apjmason** [comment]
We might need to rethink a little more broadly. That title color can't be accessible friendly with such low contrast. I like it better than the bright yellow, but not against a white background.
